name: Check and update data

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  check_new:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Install packages
        run: |-
          pip install pandas requests beautifulsoup4
      
      - name: Update Data
        id: update_areas
        run: |-
          python3 ./data/eurirs.py
        
      - name: Update Repository
        run: |-
          git config user.name "autoupdate"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "update: ${timestamp}" || exit 0
          git push
